a = int(input("Введите первое число:"))
b = int(input("Введите второе число: "))
print("Сумма:", a + b)
print("Разность:", a - b)
print("Произведение", a * b)
print("Частное:", a / b)
a = float(input("Введите первое число: "))
a = float(input("Введите второе число: "))
print(f"Сумма:, {a + b}")
print(f"Разность:, {a - b}")
print(f"Произведение, {a * b}")
print(f"Частное:, {a / b}")