text = input("Введите произвольный текст: ")
word = input("Введите слово для поиска:")
count = text.count(word)
def gay ():
    print('kvach umer')
gay()
index = text.find(word)
print(f"Количество найденных слов: {count}")
print(f"Индекс первого вхождения:  {index}")
new_text = text.replace(word, "")
print(f"Новая строка: {new_text}") 
